# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/zlib-1.2.11-on-linux_canary, last modified Wed Nov 21 14:51:31 2018
# ------------------------------------------------

package:
    name: zlib
    version: 1.2.11
source:
    fn: zlib-1.2.11.tar.gz
    sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
    url: http://zlib.net/zlib-1.2.11.tar.gz
build:
    number: '3'
    run_exports:
        - zlib >=1.2.11,<1.3.0a0
    string: h7b6447c_3
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - make 4.2.1 h1bed415_1
    host:
        - libgcc-ng 8.2.0 hdf63c60_1
    run:
        - libgcc-ng >=7.3.0
test:
    commands:
        - test -f ${PREFIX}/lib/libz.a
about:
    description: 'zlib is designed to be a free, general-purpose, lossless data-compression

        library for use on virtually any computer hardware and operating system.

        '
    dev_url: https://github.com/madler/zlib
    doc_url: http://zlib.net/manual.html
    home: http://zlib.net/
    license: zlib
    license_family: Other
    license_file: license.txt
    summary: Massively spiffy yet delicately unobtrusive compression library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - groutr
        - mingwandroid
        - msarahan
        - ocefpaf
