# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/ruamel_yaml-0.15.87-python_3.8-on-linux_64, last modified Thu Jun 25 21:57:02 2020
# ------------------------------------------------

package:
    name: ruamel_yaml
    version: 0.15.87
source:
    sha256: a736ab1d8c2d5566254a1a2ee38e7c5460520bcccd4a8f0feb25a4463735e5a7
    url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-0.15.87.tar.gz
build:
    number: '1'
    string: py38h7b6447c_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.6.20 py38_0
        - cython 0.29.20 py38he6710b0_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - python 3.8.3 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 47.3.1 py38_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - yaml 0.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - python >=3.8,<3.9.0a0
        - yaml >=0.2.5,<0.3.0a0
test:
    imports:
        - ruamel_yaml
        - ruamel_yaml.ext._ruamel_yaml
    requires:
        - pytest
about:
    description: 'ruamel.yaml is a YAML 1.2 loader/dumper package for Python.

        '
    dev_url: https://bitbucket.org/ruamel/yaml/src
    doc_source_url: https://bitbucket.org/ruamel/yaml/src/default/_doc/?at=default
    doc_url: http://yaml.readthedocs.io/en/latest/overview.html
    home: https://bitbucket.org/ruamel/yaml
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A patched copy of ruamel.yaml.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
