# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/chardet-3.0.4-python_2.7-on-linux_canary, last modified Thu Jul 25 13:49:47 2019
# ------------------------------------------------

package:
    name: chardet
    version: 3.0.4
source:
    sha256: 84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae
    url: https://pypi.io/packages/source/c/chardet/chardet-3.0.4.tar.gz
build:
    entry_points:
        - chardetect = chardet.cli.chardetect:main
    number: '1003'
    script: /tmp/build/80754af9/chardet_1564159573427/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py27_1003
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - atomicwrites 1.3.0 py27_1
        - attrs 19.1.0 py27_1
        - backports 1.0 py_2
        - ca-certificates 2019.5.15 0
        - certifi 2019.6.16 py27_0
        - configparser 3.7.4 py27_0
        - contextlib2 0.5.5 py27_0
        - funcsigs 1.0.2 py27_0
        - importlib_metadata 0.17 py27_1
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - more-itertools 5.0.0 py27_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1c h7b6447c_1
        - packaging 19.0 py27_0
        - pathlib2 2.3.4 py27_0
        - pip 19.1.1 py27_0
        - pluggy 0.12.0 py_0
        - py 1.8.0 py27_0
        - pyparsing 2.4.0 py_0
        - pytest 4.6.2 py27_0
        - pytest-runner 4.4 py_0
        - python 2.7.16 h9bab390_0
        - readline 7.0 h7b6447c_5
        - scandir 1.10.0 py27h7b6447c_0
        - setuptools 41.0.1 py27_0
        - six 1.12.0 py27_0
        - sqlite 3.29.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wcwidth 0.1.7 py27_0
        - wheel 0.33.4 py27_0
        - zipp 0.5.1 py_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=2.7,<2.8.0a0
test:
    commands:
        - chardetect --help
    imports:
        - chardet
about:
    description: 'chardet is a character encoding auto-detector in Python.

        '
    dev_url: https://github.com/chardet/chardet
    doc_source_url: https://github.com/chardet/chardet/blob/master/docs/index.rst
    doc_url: http://chardet.readthedocs.org/
    home: https://github.com/chardet/chardet
    license: LGPL2
    license_family: GPL
    license_file: LICENSE
    summary: Universal character encoding detector
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dan-blanchard
        - jschueller
        - nehaljwani
        - sigmavirus24
