# This file created by conda-build 3.18.11
# ------------------------------------------------

package:
    name: ld_impl_linux-64
    version: 2.33.1
source:
    -   folder: .
        sha256: 0cb4843da15a65a953907c96bad658283f3c4419d6bcc56bf2789db16306adb2
        url: https://ftp.gnu.org/gnu/binutils/binutils-2.33.1.tar.bz2
    -   folder: crosstool_ng
        sha256: b855a87957077c590f5d34754bee04b3a1154202f7823504c88db9eea61f4817
        url: https://github.com/isuruf/crosstool-ng/archive/931b37a4056fff186052c0e893a6682ab37e7035.tar.gz
build:
    detect_binary_files_with_prefix: false
    merge_build_host: false
    number: 7
    string: h53a641e_7
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - gcc_bootstrap_linux-64 7.3.0 h64e4fec_9
        - libgcc-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
test:
    commands:
        - x86_64-conda_cos6-linux-gnu-ld --help
about:
    home: https://www.gnu.org/software/binutils/
    license: GPL 3
    license_file:
        - COPYING
        - COPYING.LIB
        - COPYING3
        - COPYING3.LIB
    summary: A set of programming tools for creating and managing binary programs,
        object files, libraries, profile data, and assembly source code.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - frol
        - isuruf
