#! /bin/bash
#SBATCH --job-name=polar
#SBATCH --output=polar.out
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=24gb
#SBATCH --partition=computes_thin
export OMP_NUM_THREADS=16
export APBS=/scratch/opt2/apbs-1.3/bin/apbs
NULL=0   #checking if MD_run job finished or an error occured
error=0

date=`date` ; ligand=`basename "$PWD"`
echo "polar job for ligand" $ligand "started at" $date >> $WORKDIR/debuglog

while true
do
     sleep 1
     if  [ -e MD_prepare.out ]; then
         grep Error MD_prepare.out >> gromacs_errors
     fi

     if  [ -e MD_run.out ]; then
         grep Error MD_run.out >> gromacs_errors
     fi

     if  [ -e ndx.out ]; then
         grep Error ndx.out >> gromacs_errors
     fi

     if  [ -e ndx.error ]; then
        echo "ndx error" >> gromacs_errors
     fi

     nolines=`wc -l < gromacs_errors`
     if  [ $nolines -gt $NULL ]; then
         echo "one of gromacs jobs failed. exiting loop."
         error=1 ; break
     fi

     if  [ -e md_0_1.log ] #exit loop if MD_run job finished
     then
         grep Finished md_0_1.log > tmp
         if  [ -s tmp ]
         then
             error=0 ; break
         fi
     fi
done

if  [ $error -eq $NULL ]
then
    while [ ! -e md_0_1.ndx ] #wait until ndx job finishes
    do
         sleep 1
    done
    echo 1 13 | g_mmpbsa -f md_0_1.xtc -s md_0_1.tpr -n md_0_1.ndx -i polar.mdp -nomme -pbsa -decomp
fi

date=`date`
echo "polar job for ligand" $ligand "finished at" $date >> $WORKDIR/debuglog
