#! /bin/bash
#SBATCH --job-name=genex
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=
#SBATCH --cpus-per-task=1
#SBATCH --mem=48gb
#SBATCH --partition=cpu
#SBATCH --time=24:00:00
#SBATCH --output=genex.out

cancer_type=`cat $WORKDIR/cancer_type`
grep $cancer_type $vini_dir/database/cross_references > $WORKDIR/tmp
tissue=`cat $WORKDIR/tmp | awk '{print $2}'`
rm $WORKDIR/tmp 

source $vini_dir/miniconda2/bin/activate

python batch_calculate_gene_expressions.py -g ./database/genes/Uniprot_ID_list -t $tissue -o ./genes/expression_scores.csv -n ${SLURM_NTASKS}

source $vini_dir/miniconda2/bin/deactivate
