#! /bin/bash
#SBATCH --job-name=MD_prepare
#SBATCH --output=MD_prepare.out
#SBATCH --time=01:00:00
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=4gb
#SBATCH --partition=computes_thin


date=`date` ; ligand=`basename "$PWD"`
echo "MD_prepare job for ligand" $ligand "started at" $date >> $WORKDIR/debuglog

#using AMBER99SB-tip3 according to https://onlinelibrary.wiley.com/doi/full/10.1002/jccs.201900148
echo 5 | gmx pdb2gmx -ignh -f COMPLEX.pdb -o COMPLEX_processed.gro -water tip3

gmx editconf -f COMPLEX_processed.gro -o COMPLEX_newbox.gro -c -d 1.0 -bt cubic #create box

gmx solvate -cp COMPLEX_newbox.gro -cs spc216.gro -o COMPLEX_solv.gro -p topol.top #add water

gmx grompp -f ions.mdp -c COMPLEX_solv.gro -p topol.top -o ions.tpr #create atomic desc file

echo 13 | gmx -quiet -backup genion -s ions.tpr -o COMPLEX_solv_ions.gro -p topol.top -pname NA -nname CL -neutral

gmx grompp -f minim.mdp -c COMPLEX_solv_ions.gro -p topol.top -o em.tpr    #create em.tpr

gmx mdrun -ntomp 8 -v -deffnm em                                  #run energy minimization

gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr          #create nvt.tpr

date=`date`
echo "MD_prepare job for ligand" $ligand "finished at" $date >> $WORKDIR/debuglog
