#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=128
#SBATCH --mem=225gb
#SBATCH --partition=cpu
#SBATCH --job-name=prepack
#SBATCH --output=prepack.out
#SBATCH --error=prepack.err
/ceph/hpc/data/d2203-0100-users/eudraskot/rosetta_bin_linux_2021.16.61629_bundle/main/source/bin/docking_prepack_protocol.static.linuxgccrelease -database  -ensemble1 pdblist1 -ensemble2 pdblist2 -out:overwrite -multithreading:total_threads ${SLURM_CPUS_ON_NODE}
