#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=128
#SBATCH --mem=225gb
#SBATCH --partition=cpu
#SBATCH --job-name=relax
#SBATCH --output=relax.out
#SBATCH --error=relax.err
protein=$1
/ceph/hpc/data/d2203-0100-users/eudraskot/rosetta_bin_linux_2021.16.61629_bundle/main/source/bin/relax.static.linuxgccrelease -s ${protein}.pdb -out:suffix _relaxed -nstruct 1 -out:path:pdb -overwrite -multithreading:total_threads ${SLURM_CPUS_ON_NODE}
