# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/pull-recipes-asn1crypto/recipe, last modified Tue Aug  4 21:46:49 2020
# ------------------------------------------------

package:
    name: asn1crypto
    version: 1.4.0
source:
    sha256: f4f6e119474e58e04a2b1af817eb585b4fd72bdd89b998624712b5c99be7641c
    url: https://pypi.io/packages/source/a/asn1crypto/asn1crypto-1.4.0.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/asn1crypto_1596577642040/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py37_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.1.1 py37_1
        - python 3.7.7 hcff3b4d_5
        - readline 8.0 h7b6447c_0
        - setuptools 49.2.0 py37_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py37_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    commands:
        - pip check
    imports:
        - asn1crypto
    requires:
        - pip
about:
    home: https://github.com/wbond/asn1crypto
    license: MIT
    license_file: LICENSE
    summary: Python ASN.1 library with a focus on performance and a pythonic API
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jschueller
        - ocefpaf
