# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libffi-3.3-on-linux_64, last modified Mon Jul  6 16:38:18 2020
# ------------------------------------------------

package:
    name: libffi
    version: '3.3'
source:
    fn: libffi-3.3.tar.gz
    patches:
        - patches/0001-check-for-existence-of-type-before-setting.patch
    sha1: 8df6cb570c8d6596a67d1c0773bf00650154f7aa
    url: ftp://sourceware.org/pub/libffi/libffi-3.3.tar.gz
build:
    number: '2'
    run_exports:
        - libffi >=3.3,<3.4.0a0
    string: he6710b0_2
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.16.2 pl526_0
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtool 2.4.6 h7b6447c_5
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - perl 5.26.2 h14c3975_0
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - test -e $PREFIX/lib/libffi.so
        - test -e $PREFIX/lib/libffi.a
        - test -e $PREFIX/include/ffi.h
        - test -e $PREFIX/include/ffitarget.h
about:
    description: 'The libffi library provides a portable, high level programming interface

        to various calling conventions. This allows a programmer to call any

        function specified by a call interface description at run-time.

        '
    dev_url: https://github.com/libffi/libffi
    doc_url: https://sourceware.org/libffi/
    home: https://sourceware.org/libffi/
    license: Custom
    summary: A Portable Foreign Function Interface Library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - scopatz
        - stefan-balke
