# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/cryptography-3.2.1-python_3.8-on-linux_64, last modified Mon Nov 16 16:32:58 2020
# ------------------------------------------------

package:
    name: cryptography
    version: 3.2.1
source:
    sha256: d3d5e10be0cf2a12214ddee45c6bd203dab435e3d83b4560c03066eda600bfe3
    url: https://pypi.io/packages/source/c/cryptography/cryptography-3.2.1.tar.gz
build:
    number: '1'
    script: /tmp/build/80754af9/cryptography_1605544487601/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install . -vv
    string: py38h3c74f83_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 pyhd3eb1b0_3
        - cffi 1.14.3 py38h261ae71_2
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py38h06a4308_0
        - pycparser 2.20 py_2
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.1 py38h06a4308_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 pyhd3eb1b0_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - cffi !=1.11.3,>=1.8
        - libgcc-ng >=7.3.0
        - openssl >=1.1.1h,<1.1.2a
        - python >=3.8,<3.9.0a0
        - six >=1.4.1
test:
    commands:
        - pytest
    imports:
        - cryptography
        - cryptography.fernet
        - cryptography.hazmat
        - cryptography.hazmat.backends
        - cryptography.hazmat.backends.openssl
        - cryptography.hazmat.bindings
        - cryptography.hazmat.bindings.openssl
        - cryptography.hazmat.primitives
        - cryptography.hazmat.primitives.asymmetric
        - cryptography.hazmat.primitives.ciphers
        - cryptography.hazmat.primitives.kdf
        - cryptography.hazmat.primitives.twofactor
        - cryptography.x509
    requires:
        - cryptography-vectors 3.2.1.*
        - hypothesis
        - iso8601
        - pretend
        - pytest
        - pytz
    source_files:
        - tests
about:
    description: 'Cryptography is a package which provides cryptographic recipes and

        primitives to Python developers. Our goal is for it to be your

        "cryptographic standard library". It supports Python 2.6-2.7, Python 3.3+,

        and PyPy 2.6+. Cryptography includes both high level recipes, and low level

        interfaces to common cryptographic algorithms such as symmetric ciphers,

        message digests and key derivation functions.

        '
    dev_url: https://github.com/pyca/cryptography
    doc_source_url: https://github.com/pyca/cryptography/blob/master/docs/index.rst
    doc_url: http://cryptography.readthedocs.io/
    home: https://github.com/pyca/cryptography
    license: Apache-2.0 AND BSD-3-Clause AND PSF-2.0
    license_family: BSD
    license_file: LICENSE
    summary: Provides cryptographic recipes and primitives to Python developers
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - ocefpaf
