# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/aggregate/mkl-service-feedstock/recipe, last modified Mon Nov 11 16:11:29 2019
# ------------------------------------------------

package:
    name: mkl-service
    version: 2.3.0
source:
    sha256: f0c61f44f29d1264a464c14791b042826f0f74da094c3355dcc295943c46fed5
    url: https://github.com/IntelPython/mkl-service/archive/v2.3.0.tar.gz
build:
    ignore_run_exports:
        - blas
        - libgcc-ng
        - mkl-service
    number: '0'
    string: py38he904b0f_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - cython 0.29.13 py38he6710b0_0
        - intel-openmp 2019.4 243
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2019.4 243
        - mkl-devel 2019.4 243
        - mkl-include 2019.4 243
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.8.0 h0371630_2
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - mkl >=2019.4,<2020.0a0
        - python >=3.8,<3.9.0a0
        - six
test:
    commands:
        - nosetests -v mkl
    imports:
        - mkl
    requires:
        - nose
about:
    description: 'mkl-service exposes a few functions which are declared in mkl_service.h.

        It''s main purpose is to allow the user to change the number

        of CPU''s MKL is using at runtime.

        '
    dev_url: https://github.com/ContinuumIO/mkl-service
    doc_source_url: https://github.com/ContinuumIO/mkl-service/blob/master/docs/index.rst
    doc_url: https://docs.continuum.io/mkl-service/
    home: https://github.com/ContinuumIO/mkl-service
    license: 3-clause BSD
    license_family: BSD
    license_file: LICENSE.txt
    summary: Python bindings to MKL service functions
extra:
    copy_test_source_files: true
    final: true
