# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/mpi4py-3.0.3-mpi_mpich-python_3.8-on-linux_64, last modified Tue Dec  3 17:58:05 2019
# ------------------------------------------------

package:
    name: mpi4py
    version: 3.0.3
source:
    fn: mpi4py-3.0.3.tar.gz
    sha256: a9f8f549781a2757988eb536fd5f088d8b1f94c2a79ed9724c12f9a6f7d188d1
    url: https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-3.0.3.tar.gz
build:
    number: '0'
    script: pip install --no-deps .
    string: py38h028fd6f_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py38_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mpi 1.0 mpich
        - mpich 3.3.2 hc856adb_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h0371630_2
        - readline 7.0 h7b6447c_5
        - setuptools 42.0.2 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - mpich >=3.3,<3.4.0a0
        - mpich >=3.3,<3.4.0a0
        - python >=3.8,<3.9.0a0
about:
    description: 'MPI for Python provides bindings of the Message Passing Interface
        (MPI)

        standard for the Python programming language, allowing any Python program

        to exploit multiple processors.

        '
    dev_url: https://bitbucket.org/mpi4py/mpi4py
    doc_url: https://mpi4py.readthedocs.org/
    home: https://mpi4py.bitbucket.io/
    license: BSD 2-clause
    license_family: BSD
    license_file: LICENSE.rst
    summary: Python bindings for MPI
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - dalcinl
        - davidbrochart
        - minrk
        - msarahan
        - ocefpaf
