# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Sat Nov 28 23:05:45 2020
# ------------------------------------------------

package:
    name: pytz
    version: '2020.4'
source:
    sha256: 3e6b7dd2d1e0a59084bcee14a17af60c5c562cdc16d828e8eba2e683d3a7e268
    url: https://pypi.io/packages/source/p/pytz/pytz-2020.4.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/pytz_1606604771399/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: pyhd3eb1b0_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.11.8 py36h06a4308_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py36h06a4308_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.1 py36h06a4308_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 pyhd3eb1b0_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - pytz
about:
    description: 'pytz brings the Olson tz database into Python. This library allows

        accurate and cross platform timezone calculations using Python 2.4 or

        higher. It also solves the issue of ambiguous times at the end of daylight

        saving time.

        '
    dev_url: https://github.com/newvem/pytz
    doc_source_url: https://github.com/newvem/pytz/blob/master/README.txt
    doc_url: http://pythonhosted.org/pytz/
    home: http://pythonhosted.org/pytz/
    license: MIT
    license_file: LICENSE.txt
    summary: World timezone definitions, modern and historical.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
