# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/ipaddress-1.0.23-on-linux_64, last modified Tue Oct 22 16:13:30 2019
# ------------------------------------------------

package:
    name: ipaddress
    version: 1.0.23
source:
    sha256: b7f8e0369580bb4a24d5ba1d7cc29660a4a6987763faf1d8a8046830e020e7e2
    url: https://pypi.io/packages/source/i/ipaddress/ipaddress-1.0.23.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/ipaddress_1571763214396/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py27_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py27_0
        - python 2.7.17 h9bab390_0
        - readline 7.0 h7b6447c_5
        - setuptools 41.4.0 py27_0
        - sqlite 3.30.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python <=3.3
test:
    imports:
        - ipaddress
about:
    description: 'Python 3.3''s ipadress for older Python versions

        '
    doc_source_url: https://github.com/phihag/ipaddress/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/ipaddress
    home: https://github.com/phihag/ipaddress
    license: PSF 2
    license_family: PSF
    license_file: LICENSE
    summary: IPv4/IPv6 manipulation library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
