# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Tue Dec 15 20:17:11 2020
# ------------------------------------------------

package:
    name: pandas
    version: 1.1.5
source:
    sha256: f10fc41ee3c75a474d3bdf68d396f10782d013d7f67db99c0efbfd0acb99701b
    url: https://github.com/pandas-dev/pandas/releases/download/v1.1.5/pandas-1.1.5.tar.gz
build:
    number: '0'
    script:
        - /tmp/build/80754af9/pandas_1608063461786/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
            -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext"
            --global-option="-j${CPU_COUNT}" --no-use-pep517
    string: py38ha9443f7_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2020.12.8 h06a4308_0
        - certifi 2020.12.5 py38h06a4308_0
        - cython 0.29.21 py38h2531618_0
        - intel-openmp 2020.2 254
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2020.2 256
        - mkl-service 2.3.0 py38he904b0f_0
        - mkl_fft 1.2.0 py38h23d657b_0
        - mkl_random 1.1.1 py38h0573a6f_0
        - ncurses 6.2 he6710b0_1
        - numpy 1.16.6 py38hbc911f0_0
        - numpy-base 1.16.6 py38hde5b4d6_0
        - openssl 1.1.1i h27cfd23_0
        - pip 20.3.1 py38h06a4308_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 51.0.0 py38h06a4308_2
        - six 1.15.0 py38h06a4308_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.36.2 pyhd3eb1b0_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - numpy >=1.16.6,<2.0a0
        - python >=3.8,<3.9.0a0
        - python-dateutil >=2.7.3
        - pytz >=2017.2
test:
    imports:
        - pandas
about:
    home: http://pandas.pydata.org
    license: BSD-3-Clause
    license_file: LICENSE
    summary: High-performance, easy-to-use data structures and data analysis tools.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - TomAugspurger
        - WillAyd
        - jorisvandenbossche
        - jreback
        - msarahan
        - ocefpaf
        - simonjayhawkins
