# This file created by conda-build 3.12.0
# ------------------------------------------------

package:
    name: libgcc-ng
    version: 9.1.0
source:
    path: .
build:
    binary_relocation: false
    detect_binary_files_with_prefix: false
    missing_dso_whitelist:
        - '*'
    number: 0
    string: hdf63c60_0
about:
    home: https://gcc.gnu.org/onlinedocs/gccint/Libgcc.html
    license: GPL
    summary: The GCC low-level runtime library
extra:
    copy_test_source_files: true
    final: true
